name: FirstPlugin
version: '1.0-SNAPSHOT'
main: me.aaddev.firstPlugin.FirstPlugin
api-version: '1.21'
authors: [ aad.dev, KetamineKey ]
description: my first plugin ever
website: https://github.com/aad-1083474
